#!/usr/bin/env bash
#
# Download UV binaries for all supported platforms.
#
# Usage: ./scripts/download-uv.sh <version>
# Example: ./scripts/download-uv.sh 0.5.14
#
# This script downloads UV binaries from GitHub releases and extracts them
# to vendor/uv/{platform}/uv[.exe] for embedding in the Ticca binary.
#
# Security features:
# - HTTPS-only downloads with TLS 1.2+
# - SHA256 checksum verification for all archives
#
# The script is idempotent - skips platforms where the binary already exists.

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Platforms to download
PLATFORMS=(
    "x86_64-unknown-linux-gnu"
    "aarch64-unknown-linux-gnu"
    "x86_64-apple-darwin"
    "aarch64-apple-darwin"
    "x86_64-pc-windows-msvc"
)

# Base URL for UV releases
BASE_URL="https://github.com/astral-sh/uv/releases/download"

# Output directory
VENDOR_DIR="vendor/uv"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

usage() {
    echo "Usage: $0 <version> [--print-checksums]"
    echo "Example: $0 0.5.14"
    echo ""
    echo "Downloads UV binaries for all supported platforms to vendor/uv/"
    echo ""
    echo "Options:"
    echo "  --print-checksums  Print SHA256 checksums for embedding in Rust code"
    echo ""
    echo "Security: All downloads are verified against SHA256 checksums."
    exit 1
}

# Print checksums in Rust constant format for embedding
print_rust_checksums() {
    echo ""
    echo "// ============================================================================"
    echo "// Platform-specific SHA256 checksums for UV binary integrity verification"
    echo "// Generated by: ./scripts/download-uv.sh <version> --print-checksums"
    echo "// ============================================================================"
    echo ""
    
    local checksum_cmd
    if command -v sha256sum &> /dev/null; then
        checksum_cmd="sha256sum"
    elif command -v shasum &> /dev/null; then
        checksum_cmd="shasum -a 256"
    else
        log_error "Neither sha256sum nor shasum found."
        return 1
    fi
    
    for platform in "${PLATFORMS[@]}"; do
        local binary_name
        binary_name=$(get_binary_name "$platform")
        local binary_path="$VENDOR_DIR/$platform/$binary_name"
        
        if [[ ! -f "$binary_path" ]]; then
            log_error "Binary not found: $binary_path"
            log_error "Run '$0 <version>' first to download binaries."
            return 1
        fi
        
        local checksum
        checksum=$($checksum_cmd "$binary_path" | awk '{print $1}')
        
        # Map platform to Rust cfg
        local target_os target_arch
        case "$platform" in
            x86_64-unknown-linux-gnu)
                target_os="linux"; target_arch="x86_64" ;;
            aarch64-unknown-linux-gnu)
                target_os="linux"; target_arch="aarch64" ;;
            x86_64-apple-darwin)
                target_os="macos"; target_arch="x86_64" ;;
            aarch64-apple-darwin)
                target_os="macos"; target_arch="aarch64" ;;
            x86_64-pc-windows-msvc)
                target_os="windows"; target_arch="x86_64" ;;
        esac
        
        echo "#[cfg(all(target_os = \"$target_os\", target_arch = \"$target_arch\"))]"
        echo "const UV_EXPECTED_SHA256: &str = \"$checksum\";"
        echo ""
    done
}

# Check if curl or wget is available
get_downloader() {
    if command -v curl &> /dev/null; then
        echo "curl"
    elif command -v wget &> /dev/null; then
        echo "wget"
    else
        log_error "Neither curl nor wget found. Please install one of them."
        exit 1
    fi
}

# Download a file with HTTPS enforcement
download() {
    local url="$1"
    local output="$2"
    local downloader
    downloader=$(get_downloader)

    if [[ "$downloader" == "curl" ]]; then
        # Security: Enforce HTTPS and TLS 1.2+
        curl --proto '=https' --tlsv1.2 -fsSL "$url" -o "$output"
    else
        # Security: Enforce HTTPS only
        wget --https-only -q "$url" -O "$output"
    fi
}

# Verify file against SHA256 checksum (downloads sidecar checksum file)
verify_checksum() {
    local version="$1"
    local file="$2"
    local archive_name="$3"
    
    # Download the sidecar checksum file for this specific archive
    local checksum_url="$BASE_URL/$version/${archive_name}.sha256"
    local temp_checksum
    temp_checksum=$(mktemp)
    trap "rm -f '$temp_checksum'" RETURN
    
    if ! download "$checksum_url" "$temp_checksum"; then
        log_error "Failed to download checksum file for $archive_name"
        return 1
    fi
    
    # Extract expected checksum (format: "checksum  filename" or "checksum *filename")
    local expected_checksum
    expected_checksum=$(awk '{print $1}' "$temp_checksum")
    
    if [[ -z "$expected_checksum" ]]; then
        log_error "Could not parse checksum from checksum file for $archive_name"
        return 1
    fi
    
    # Calculate actual checksum
    local actual_checksum
    if command -v sha256sum &> /dev/null; then
        actual_checksum=$(sha256sum "$file" | awk '{print $1}')
    elif command -v shasum &> /dev/null; then
        actual_checksum=$(shasum -a 256 "$file" | awk '{print $1}')
    else
        log_error "Neither sha256sum nor shasum found. Cannot verify checksum."
        return 1
    fi
    
    if [[ "$expected_checksum" != "$actual_checksum" ]]; then
        log_error "Checksum verification failed for $archive_name!"
        log_error "Expected: $expected_checksum"
        log_error "Actual:   $actual_checksum"
        log_error "This could indicate a corrupted download or tampering."
        return 1
    fi
    
    log_info "Checksum verified for $archive_name"
    return 0
}

# Get the binary name for a platform
get_binary_name() {
    local platform="$1"
    if [[ "$platform" == *"windows"* ]]; then
        echo "uv.exe"
    else
        echo "uv"
    fi
}

# Get the archive extension for a platform
get_archive_ext() {
    local platform="$1"
    if [[ "$platform" == *"windows"* ]]; then
        echo "zip"
    else
        echo "tar.gz"
    fi
}

# Extract archive and get the uv binary
extract_binary() {
    local archive="$1"
    local platform="$2"
    local output_dir="$3"
    local binary_name
    binary_name=$(get_binary_name "$platform")
    local ext
    ext=$(get_archive_ext "$platform")

    # Create a temp directory for extraction
    local temp_dir
    temp_dir=$(mktemp -d)
    trap "rm -rf '$temp_dir'" RETURN

    if [[ "$ext" == "zip" ]]; then
        # Windows zip file - extracts directly (no subdirectory)
        unzip -q "$archive" -d "$temp_dir"
    else
        # Unix tar.gz file - extracts to uv-{platform}/ subdirectory
        tar -xzf "$archive" -C "$temp_dir"
    fi

    # Find the binary - location differs between zip and tar.gz
    local extracted_binary
    if [[ "$ext" == "zip" ]]; then
        # Windows zip extracts directly to temp dir
        extracted_binary="$temp_dir/$binary_name"
    else
        # Unix tar.gz extracts to uv-{platform}/ subdirectory
        extracted_binary="$temp_dir/uv-$platform/$binary_name"
    fi
    
    if [[ ! -f "$extracted_binary" ]]; then
        log_error "Binary not found at expected path: $extracted_binary"
        log_error "Contents of temp dir:"
        find "$temp_dir" -type f >&2
        return 1
    fi

    mkdir -p "$output_dir"
    mv "$extracted_binary" "$output_dir/$binary_name"

    # Make executable on Unix
    if [[ "$binary_name" == "uv" ]]; then
        chmod +x "$output_dir/$binary_name"
    fi
}

# Download and extract UV for a specific platform
download_platform() {
    local version="$1"
    local platform="$2"
    local output_dir="$VENDOR_DIR/$platform"
    local binary_name
    binary_name=$(get_binary_name "$platform")
    local binary_path="$output_dir/$binary_name"

    # Check if already exists
    if [[ -f "$binary_path" ]]; then
        log_info "Skipping $platform (already exists)"
        return 0
    fi

    local ext
    ext=$(get_archive_ext "$platform")
    local archive_name="uv-$platform.$ext"
    local url="$BASE_URL/$version/$archive_name"

    log_info "Downloading UV $version for $platform..."

    # Download to temp file
    local temp_archive
    temp_archive=$(mktemp)
    trap "rm -f '$temp_archive'" RETURN

    if ! download "$url" "$temp_archive"; then
        log_error "Failed to download $url"
        return 1
    fi

    # Verify checksum
    if ! verify_checksum "$version" "$temp_archive" "$archive_name"; then
        log_error "Checksum verification failed for $platform"
        return 1
    fi

    log_info "Extracting $platform..."
    if ! extract_binary "$temp_archive" "$platform" "$output_dir"; then
        log_error "Failed to extract binary for $platform"
        return 1
    fi

    log_info "Successfully installed UV for $platform"
}

# Main
main() {
    if [[ $# -lt 1 ]]; then
        usage
    fi

    local version="$1"
    local print_checksums=false
    
    # Check for --print-checksums flag
    if [[ $# -ge 2 && "$2" == "--print-checksums" ]]; then
        print_checksums=true
    fi

    # Validate version format (basic check)
    if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        log_error "Invalid version format: $version"
        log_error "Expected format: X.Y.Z (e.g., 0.5.14)"
        exit 1
    fi

    # If just printing checksums, do that and exit
    if [[ "$print_checksums" == true ]]; then
        print_rust_checksums
        exit 0
    fi

    log_info "Downloading UV version $version for all platforms"
    log_info "Output directory: $VENDOR_DIR"
    echo ""

    # Create vendor directory
    mkdir -p "$VENDOR_DIR"

    # Write version file
    echo "$version" > "$VENDOR_DIR/VERSION"

    local failed=0
    for platform in "${PLATFORMS[@]}"; do
        if ! download_platform "$version" "$platform"; then
            log_error "Failed to download $platform"
            ((failed++)) || true
        fi
    done

    echo ""
    if [[ $failed -gt 0 ]]; then
        log_error "$failed platform(s) failed to download"
        exit 1
    else
        log_info "All platforms downloaded successfully!"
        log_info "All checksums verified!"
        log_info "Structure:"
        find "$VENDOR_DIR" -type f | sort | sed 's/^/  /'
        echo ""
        log_info "To update embedded checksums in Rust code, run:"
        echo "  $0 $version --print-checksums"
    fi
}

main "$@"
