"""Core type definitions for Ticca Agent.

This module defines all the fundamental data types used for agent
communication, including requests, responses, messages, and streaming chunks.

All types are Pydantic v2 models with full validation and serialization support.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class MessageRole(str, Enum):
    """Role of a message in the conversation.

    Defines the participant type for each message in the conversation
    history, following the standard chat completion API conventions.
    """

    SYSTEM = "system"
    """System instructions that guide the AI's behavior."""

    USER = "user"
    """Messages from the human user."""

    ASSISTANT = "assistant"
    """Messages generated by the AI assistant."""

    TOOL = "tool"
    """Results from tool/function calls."""


class Message(BaseModel):
    """A single message in the conversation.

    Represents one message in the conversation history with its content,
    role, and optional metadata for tool calls.

    Attributes:
        role: The role of the message sender.
        content: The text content of the message.
        name: Optional name for the message sender.
        tool_call_id: ID linking tool results to their calls.
        tool_calls: List of tool calls made by the assistant.
    """

    role: MessageRole = Field(description="Role of the message sender")
    content: str = Field(description="Text content of the message")
    name: str | None = Field(
        default=None,
        description="Optional name for the message sender",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="ID linking tool results to their original calls",
    )
    tool_calls: list[dict[str, Any]] | None = Field(
        default=None,
        description="List of tool calls made in this message",
    )

    model_config = {"frozen": True}


class TokenUsage(BaseModel):
    """Token usage statistics for a request/response.

    Tracks the number of tokens consumed for billing and monitoring purposes.

    Attributes:
        prompt_tokens: Tokens in the input prompt.
        completion_tokens: Tokens in the generated response.
        total_tokens: Sum of prompt and completion tokens.
    """

    prompt_tokens: int = Field(ge=0, description="Tokens used in the prompt")
    completion_tokens: int = Field(ge=0, description="Tokens in the completion")
    total_tokens: int = Field(ge=0, description="Total tokens used")

    model_config = {"frozen": True}


class AgentRequest(BaseModel):
    """Request to an AI agent for generation.

    Encapsulates all the information needed to generate a response,
    including the conversation history and generation parameters.

    Attributes:
        request_id: Unique identifier for this request.
        messages: Conversation history as a list of messages.
        model: Specific model to use (provider-dependent).
        temperature: Sampling temperature (0.0 to 2.0).
        max_tokens: Maximum tokens to generate.
        stop_sequences: Optional sequences that stop generation.
        metadata: Additional request-specific metadata.
        created_at: Timestamp when request was created.
    """

    request_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for this request",
    )
    messages: list[Message] = Field(
        min_length=1,
        description="Conversation history",
    )
    model: str | None = Field(
        default=None,
        description="Model identifier (uses provider default if not specified)",
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Sampling temperature for generation",
    )
    max_tokens: int | None = Field(
        default=None,
        ge=1,
        le=1_000_000,
        description="Maximum tokens to generate",
    )
    stop_sequences: list[str] | None = Field(
        default=None,
        description="Sequences that trigger generation stop",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional request metadata",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Request creation timestamp",
    )

    model_config = {"frozen": True}


class AgentResponse(BaseModel):
    """Response from an AI agent.

    Contains the generated content along with metadata about the generation
    process including token usage and timing information.

    Attributes:
        request_id: ID of the request that generated this response.
        response_id: Unique identifier for this response.
        content: Generated text content.
        model: Model that generated this response.
        usage: Token usage statistics.
        finish_reason: Why generation stopped.
        tool_calls: Any tool calls in the response.
        metadata: Additional response metadata.
        created_at: Response creation timestamp.
    """

    request_id: UUID = Field(description="ID of the originating request")
    response_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for this response",
    )
    content: str = Field(description="Generated text content")
    model: str = Field(description="Model that generated this response")
    usage: TokenUsage | None = Field(
        default=None,
        description="Token usage statistics",
    )
    finish_reason: str = Field(
        default="stop",
        description="Reason generation stopped (stop, length, tool_calls, etc.)",
    )
    tool_calls: list[dict[str, Any]] | None = Field(
        default=None,
        description="Tool calls made by the assistant",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional response metadata",
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Response creation timestamp",
    )

    model_config = {"frozen": True}


class StreamChunk(BaseModel):
    """A single chunk from a streaming response.

    Represents an incremental piece of a streaming AI response,
    enabling real-time display of generated content.

    Attributes:
        request_id: ID of the originating request.
        chunk_index: Sequential index of this chunk (0-based).
        delta: New content in this chunk.
        finish_reason: Set on the final chunk to indicate completion.
        usage: Token usage (typically only on final chunk).
        is_final: Whether this is the last chunk.
    """

    request_id: UUID = Field(description="ID of the originating request")
    chunk_index: int = Field(ge=0, description="Sequential chunk index")
    delta: str = Field(default="", description="New content in this chunk")
    finish_reason: str | None = Field(
        default=None,
        description="Set on final chunk to indicate why streaming stopped",
    )
    usage: TokenUsage | None = Field(
        default=None,
        description="Token usage (typically only present on final chunk)",
    )
    is_final: bool = Field(
        default=False,
        description="Whether this is the final chunk",
    )

    model_config = {"frozen": True}


class ModelInfo(BaseModel):
    """Information about an available AI model.

    Describes a model's capabilities and constraints for display
    in the UI and for request validation.

    Attributes:
        id: Unique model identifier.
        name: Human-readable model name.
        provider: Provider that offers this model.
        max_tokens: Maximum context window size.
        supports_streaming: Whether model supports streaming.
        supports_tools: Whether model supports tool/function calls.
        supports_vision: Whether model supports image inputs.
        description: Optional model description.
    """

    id: str = Field(description="Unique model identifier")
    name: str = Field(description="Human-readable model name")
    provider: str = Field(description="Provider offering this model")
    max_tokens: int = Field(
        ge=1,
        description="Maximum context window size in tokens",
    )
    supports_streaming: bool = Field(
        default=True,
        description="Whether model supports streaming responses",
    )
    supports_tools: bool = Field(
        default=False,
        description="Whether model supports tool/function calling",
    )
    supports_vision: bool = Field(
        default=False,
        description="Whether model supports image inputs",
    )
    description: str | None = Field(
        default=None,
        description="Optional description of model capabilities",
    )

    model_config = {"frozen": True}
